package code.lib.util

object Languages {

  /*
   * Source: Wikipedia
   */
  val l = List(
	"A Sharp (.NET)",
	"A Sharp (Axiom)",
	"A-0 System",
	"A+ (programming language)",
	"A++",
	"ABAP",
	"ABC (programming language)",
	"ABC ALGOL",
	"ABLE (programming language)",
	"ABSET",
	"ABSYS",
	"Abundance (programming language)",
	"ACC (programming language)",
	"Accent (programming language)",
	"Distributed Application Specification Language",
	"LGP-30",
	"Action! (programming language)",
	"ActionScript",
	"Ada (programming language)",
	"Adenine (programming language)",
	"Agda (theorem prover)",
	"Agilent VEE",
	"Agora (programming language)",
	"AIMMS",
	"Alef (programming language)",
	"Algebraic Logic Functional programming language",
	"ALGOL 58",
	"ALGOL 60",
	"ALGOL 68",
	"Alice (programming language)",
	"Alma-0",
	"AmbientTalk",
	"Amiga E",
	"AMOS (programming language)",
	"AMPL",
	"APL (programming language)",
	"AppleScript",
	"Arc (programming language)",
	"ARexx",
	"Argus (programming language)",
	"AspectJ",
	"ASP.NET",
	"Assembly language",
	"ATS (programming language)",
	"Ateji PX",
	"AutoHotkey",
	"Autocoder",
	"AutoIt",
	"AutoLISP",
	"Averest",
	"AWK",
	"Axum (programming language)",
	"B (programming language)",
	"Babbage (programming language)",
	"Bash (Unix shell)",
	"BASIC",
	"Bc (programming language)",
	"BCPL",
	"BeanShell",
	"Batch file",
	"Bertrand (programming language)",
	"BETA",
	"Bigwig (programming language)",
	"Bistro (programming language)",
	"BitC",
	"BLISS (programming language)",
	"Blue (programming language)",
	"Bon (programming language)",
	"Boo (programming language)",
	"Boomerang (programming language)",
	"Bourne shell",
	"Qualcomm Brew",
	"Business Process Execution Language",
	"BUGSYS",
	"BuildProfessional",
	"C (programming language)",
	"C--",
	"C++",
	"C Sharp (programming language)",
	"C/AL",
	"Caché ObjectScript",
	"C Shell",
	"Caml",
	"Candle (programming language)",
	"Cayenne (programming language)",
	"CDuce",
	"Cecil (programming language)",
	"Cel (programming language)",
	"Cesil",
	"Ceylon (programming language)",
	"ColdFusion Markup Language",
	"Cg (programming language)",
	"Ch (computer programming)",
	"Chapel (programming language)",
	"CHAIN (programming language)",
	"Charity (programming language)",
	"Charm (language)",
	"Chef (programming language)",
	"CHILL",
	"CHIP-8",
	"Chomski",
	"ChucK",
	"CICS",
	"Cilk",
	"AS/400 Control Language",
	"Claire (programming language)",
	"Clarion (programming language)",
	"Clean (programming language)",
	"Clipper (programming language)",
	"CLIST",
	"Clojure",
	"CLU (programming language)",
	"CMS-2 (programming language)",
	"COBOL",
	"CobolScript",
	"Cobra (programming language)",
	"CODE (programming language)",
	"CoffeeScript",
	"Cola (programming language)",
	"ColdC",
	"ColdFusion",
	"Cool (programming language)",
	"COMAL",
	"Combined Programming Language",
	"Common Intermediate Language",
	"Common Lisp",
	"COMPASS",
	"Component Pascal",
	"COMIT",
	"Constraint Handling Rules",
	"Converge (programming language)",
	"Coral 66",
	"Corn (emulator)",
	"CorVision",
	"Coq",
	"COWSEL",
	"Combined Programming Language",
	"C shell",
	"Communicating sequential processes",
	"Csound",
	"Curl (programming language)",
	"Curry (programming language)",
	"Cyclone (programming language)",
	"Cython",
	"D (programming language)",
	"DASL (programming language)",
	"Distributed Application Specification Language",
	"Dart (programming language)",
	"DataFlex",
	"Datalog",
	"DATATRIEVE",
	"DBase",
	"Dc (computer program)",
	"DIGITAL Command Language",
	"Deesel",
	"Delphi (programming language)",
	"Dink Smallwood",
	"DIBOL",
	"Sepandar Kamvar",
	"Draco (programming language)",
	"Dylan (programming language)",
	"DYNAMO (programming language)",
	"E (programming language)",
	"E Sharp (programming language)",
	"Ease (programming language)",
	"PL/I",
	"Easytrieve",
	"ECMAScript",
	"Edinburgh IMP",
	"EGL (programming language)",
	"Eiffel (programming language)",
	"ELAN (programming language)",
	"Emacs Lisp",
	"Emerald (programming language)",
	"Epigram (programming language)",
	"Erlang (programming language)",
	"Es (Unix shell)",
	"Escapade (programming language)",
	"Escher (programming language)",
	"Executive Systems Problem Oriented Language",
	"Esterel",
	"Etoys (programming language)",
	"Euclid (programming language)",
	"Euler (programming language)",
	"Euphoria (programming language)",
	"EusLisp Robot Programming Language",
	"CMS EXEC",
	"EXEC 2",
	"F (programming language)",
	"F Sharp (programming language)",
	"Factor (programming language)",
	"Falcon (programming language)",
	"Fancy (programming language)",
	"Fantom (programming language)",
	"FAUST (programming language)",
	"Felix (programming language)",
	"Ferite",
	"FFP (programming language)",
	"Fjölnir (programming language)",
	"FL (programming language)",
	"Flavors (programming language)",
	"Flex (programming language)",
	"FLOW-MATIC",
	"FOCAL (programming language)",
	"FOCUS",
	"FOIL (programming language)",
	"FORMAC (programming language)",
	"Formula language",
	"Forth (programming language)",
	"Fortran",
	"Fortress (programming language)",
	"FoxBase",
	"FoxPro (disambiguation)",
	"FP (programming language)",
	"FPr (programming language)",
	"Franz Lisp",
	"Frink",
	"F-Script (programming language)",
	"fr:FSProg",
	"G (programming language)",
	"Game Maker Language",
	"GameMonkey Script",
	"General Algebraic Modeling System",
	"GAP computer algebra system",
	"G-code",
	"Genie (programming language)",
	"Geometric Description Language",
	"Gibiane",
	"Generic Java",
	"GEORGE (programming language)",
	"GLSL",
	"GNU E",
	"Golden master",
	"Go (programming language)",
	"Go! (programming language)",
	"Game Oriented Assembly Lisp",
	"Gödel (programming language)",
	"Godiva (programming language)",
	"MAD (programming language)",
	"Goo (programming language)",
	"Gosu (programming language)",
	"IBM 1620",
	"GPSS",
	"Computer Sciences Corporation",
	"GRASS (programming language)",
	"Groovy (programming language)",
	"HAL/S",
	"Hamilton C shell",
	"Harbour (software)",
	"Hartmann pipeline",
	"Haskell (programming language)",
	"Haxe",
	"High Level Assembly",
	"High Level Shader Language",
	"Hop (software)",
	"Hope (programming language)",
	"Hugo (programming language)",
	"Hume (language)",
	"HyperTalk",
	"IBM Basic assembly language",
	"IBM HAScript",
	"IBM Informix-4GL",
	"IBM RPG",
	"ICI (programming language)",
	"Icon (programming language)",
	"Id (programming language)",
	"IDL (programming language)",
	"Idris (programming language)",
	"IMP (programming language)",
	"Inform",
	"Io (programming language)",
	"Ioke (programming language)",
	"Information Processing Language",
	"IPTSCRAE",
	"ISLISP",
	"ISPF",
	"ISWIM",
	"J (programming language)",
	"J Sharp",
	"Visual J++",
	"JADE (programming language)",
	"Jako (programming language)",
	"JAL (compiler)",
	"Janus (programming language)",
	"JASS",
	"Java (programming language)",
	"JavaScript",
	"Job Control Language",
	"JEAN",
	"Join Java",
	"JOSS",
	"Joule (programming language)",
	"JOVIAL",
	"Joy (programming language)",
	"JScript",
	"JavaFX Script",
	"Julia (programming language)",
	"K (programming language)",
	"Kaleidoscope (programming language)",
	"Karel (programming language)",
	"Karel++",
	"Kaya (programming language)",
	"IntelliCorp (Software)",
	"Knowledge Interchange Format",
	"Kojo (programming language)",
	"Kent Recursive Calculator",
	"KRL (programming language)",
	"KUKA",
	"KRYPTON",
	"Korn shell",
	"L (programming language)",
	"L Sharp",
	"LabVIEW",
	"Ladder logic",
	"Lagoona (programming language)",
	"LANSA (development environment)",
	"Lasso (programming language)",
	"LaTeX",
	"Lava (programming language)",
	"LC-3",
	"Leadwerks Engine",
	"Leda (programming language)",
	"Lego Mindstorms",
	"Little Implementation Language",
	"LilyPond",
	"Limbo (programming language)",
	"Limnor",
	"LINC",
	"Lingo (programming language)",
	"Linoleum (programming language)",
	"LIS (programming language)",
	"Language for Instruction Set Architecture",
	"Lisaac",
	"Lisp (programming language)",
	"Lite-C",
	"Lithe (programming language)",
	"Little b (programming language)",
	"Logo (programming language)",
	"Logtalk",
	"LPC (programming language)",
	"LSE (programming language)",
	"Linden Scripting Language",
	"LiveCode",
	"Lua (programming language)",
	"Lucid (programming language)",
	"Lustre (programming language)",
	"LYaPAS",
	"Lynx (programming language)",
	"M (programming language)",
	"M2001",
	"M4 (computer language)",
	"Machine code",
	"MAD (programming language)",
	"MAD (programming language)",
	"Magik (programming language)",
	"Magma computer algebra system",
	"Make (software)",
	"Maple (software)",
	"MAPPER",
	"MARK IV (software)",
	"Mary (programming language)",
	"Microsoft Macro Assembler",
	"Mathematica",
	"MATLAB",
	"Maxima (software)",
	"Max (software)",
	"Autodesk 3ds Max",
	"Maya Embedded Language",
	"MDL (programming language)",
	"Mercury (programming language)",
	"Mesa (programming language)",
	"Metacard",
	"Metafont",
	"MetaL (programming language)",
	"Microassembler",
	"MicroScript (programming language)",
	"MIIS (programming language)",
	"MillScript",
	"MIMIC",
	"Mirah (programming language)",
	"Miranda (programming language)",
	"MIVA Script",
	"ML (programming language)",
	"Moby (programming language)",
	"Model 204",
	"Modelica",
	"Modula",
	"Modula-2",
	"Modula-3",
	"Mohol programming languages",
	"MOO (programming language)",
	"Mortran",
	"Mouse (programming language)",
	"MPD (programming language)",
	"Common Intermediate Language",
	"MIRC scripting language",
	"MUMPS",
	"Napier88",
	"Netwide Assembler",
	"NATURAL",
	"Neko (programming language)",
	"Nemerle",
	"NESL",
	"Net.Data",
	"NetLogo",
	"NetRexx",
	"NewLISP",
	"NEWP",
	"Newspeak (programming language)",
	"NewtonScript",
	"NGL (programming language)",
	"Nial",
	"Nice (programming language)",
	"Nickle (programming language)",
	"NORD Programming Language",
	"Not eXactly C",
	"Not Quite C",
	"Nu (programming language)",
	"Nullsoft Scriptable Install System",
	"NWScript",
	"O:XML",
	"Oak (programming language)",
	"Oberon (programming language)",
	"Obix programming language",
	"OBJ2",
	"Object Lisp",
	"ObjectLOGO",
	"Object REXX",
	"Object Pascal",
	"Objective-C",
	"Objective-J",
	"Obliq",
	"Obol (programming language)",
	"OCaml",
	"Occam (programming language)",
	"Occam-π",
	"GNU Octave",
	"OmniMark",
	"Onyx (programming language)",
	"Opa (programming language)",
	"Opal (programming language)",
	"OpenEdge Advanced Business Language",
	"Open Programming Language",
	"OPS5",
	"OptimJ",
	"Orc (programming language)",
	"ORCA/Modula-2",
	"Oriel (scripting language)",
	"Orwell (programming language)",
	"Oxygene (programming language)",
	"Oz (programming language)",
	"P Sharp",
	 "class=",
	"PARI/GP",
	"Pascal (programming language)",
	"Pawn (programming language)",
	"PCASTL",
	"Programming language for Computable Functions",
	"PEARL (programming language)",
	"PeopleCode",
	"Perl",
	"Perl Data Language",
	"PHP",
	"Phrogram",
	"Pico (programming language)",
	"Pict (programming language)",
	"Pike (programming language)",
	"PIKT",
	"PILOT",
	"Hartmann pipeline",
	"Pizza (programming language)",
	"PL-11",
	"PL/0",
	"Programming Language for Business",
	"PL/C",
	"PL/I",
	"PL/M",
	"PL/P",
	"PL/SQL",
	"PL360",
	"PLANC",
	"Plankalkül",
	"PLEX (programming language)",
	"PLEXIL",
	"Plus (programming language)",
	"POP-11",
	"PostScript",
	"Amiga E",
	"Powerhouse (programming language)",
	"PowerBuilder",
	"PowerShell",
	"Polymorphic Programming Language",
	"Processing (programming language)",
	"Processing.js",
	"Prograph",
	"PROIV",
	"Prolog",
	"Visual Prolog",
	"Promela",
	"Protel",
	"ProvideX",
	"Pro*C",
	"Pure (programming language)",
	"Python (programming language)",
	"Q (equational programming language)",
	"Q (programming language from Kx Systems)",
	"Qalb (programming language)",
	"QBasic",
	"Qi (programming language)",
	"Qore (programming language)",
	"QtScript",
	"QuakeC",
	"Quantum programming",
	"R (programming language)",
	"R++",
	"Racket (programming language)",
	"RAPID",
	"Rapira",
	"Ratfiv",
	"Ratfor",
	"Rc",
	"REBOL",
	"Core War",
	"REFAL",
	"Reia (programming language)",
	"Revolution (programming language)",
	"Rex (language)",
	"REXX",
	"Rlab",
	"ROOP (programming language)",
	"IBM RPG",
	"RPL (programming language)",
	"Robot Battle",
	"RTL/2",
	"Ruby (programming language)",
	"Rust (programming language)",
	"S (programming language)",
	"S2 (programming language)",
	"S3 (programming language)",
	"S-Lang (programming language)",
	"S-PLUS",
	"SA-C (programming language)",
	"SabreTalk",
	"SAIL (programming language)",
	"SALSA (programming language)",
	"SAM76",
	"SAS System",
	"SASL (programming language)",
	"Sather",
	"Sawzall (programming language)",
	"Superbase database",
	"Scala (programming language)",
	"Scheme (programming language)",
	"Scilab",
	"Scratch (programming language)",
	"Script.NET",
	"Sed",
	"Seed7",
	"Self (programming language)",
	"SenseTalk",
	"SequenceL",
	"SETL",
	"Shift Script",
	"Superbase database",
	"SIMSCRIPT",
	"Simula",
	"Simulink",
	"SISAL",
	"SLIP (programming language)",
	"SMALL",
	"Smalltalk",
	"SmallBASIC",
	"Standard ML",
	"SNOBOL",
	"Snowball programming language",
	"Secure Operations Language",
	"Span (programming language)",
	"SPARK (programming language)",
	"Parallax Propeller",
	"SP/k",
	"IBM 1401 Symbolic Programming System",
	"Squeak",
	"Squirrel (programming language)",
	"SR (programming language)",
	"S/SL programming language",
	"Starlogo",
	"Strand (programming language)",
	"Stata",
	"Stateflow",
	"Subtext (programming language)",
	"SuperCollider",
	"SuperTalk",
	"SYMPL",
	"SyncCharts",
	"SystemVerilog",
	"T (programming language)",
	"TACL",
	"TACPOL (programming language)",
	"TADS",
	"Transaction Application Language",
	"Tcl",
	"Tea (programming language)",
	"Text Editor and Corrector",
	"TELCOMP",
	"TeX",
	"Text Executive Programming Language",
	"Tensilica Instruction Extension",
	"Timber (programming language)",
	"TMG (language)",
	"Tom (pattern matching language)",
	"TOM (object-oriented programming language)",
	"Clarion (programming language)",
	"Text Processing Utility",
	"TRAC (programming language)",
	"TTM (programming language)",
	"Transact-SQL",
	"TTCN",
	"Turing (programming language)",
	"TUTOR (programming language)",
	"TXL (programming language)",
	"TypeScript",
	"Ubercode",
	"UCSD Pascal",
	"Unicon (programming language)",
	"Uniface (programming language)",
	"UNITY (programming language)",
	"Unix shell",
	"UnrealScript",
	"Vala (programming language)",
	"Visual Basic for Applications",
	"VBScript",
	"Verilog",
	"VHDL",
	"Visual Basic",
	"Visual Basic .NET",
	"Microsoft Visual C++",
	"Microsoft Visual C Sharp",
	"Visual DataFlex",
	"Visual DialogScript",
	"Visual Fortran",
	"Visual FoxPro",
	"Visual J++",
	"Visual J",
	"Visual Objects",
	"VSXu",
	"Vvvv",
	"WATFIV (programming language)",
	"WebDNA",
	"WebQL",
	"Windows PowerShell",
	"Winbatch",
	"Microsoft Dynamics AX",
	"X Sharp (programming language)",
	"X10 (programming language)",
	"XBL",
	"XC Programming Language",
	"XHarbour",
	"XL (programming language)",
	"XOTcl",
	"XPL",
	"XPL0",
	"XQuery",
	"XSB",
	"XSL Transformations",
	"Yorick (programming language)",
	"YQL (programming language)",
	"Z notation",
	"Zeno (programming language)",
	"ZOPL",
	"ZPL (programming language)")


}